Updated build scripts

diff --git a/build-deb b/build-deb
--- a/build-deb
+++ b/build-deb
@@ -1,4 +1,4 @@
-#!/bin/bash -e
+#!/usr/bin/env bash
 #
 # Debian Packaging Scripts
 # Copyright (C) 2002-2019 by Thomas Dreibholz
@@ -17,6 +17,9 @@
 # along with this program.  If not, see <http://www.gnu.org/licenses/>.
 #
 # Contact: dreibh@iem.uni-due.de
+
+# Bash options:
+set -e
 
 
 # ====== Obtain package and version information =============================
@@ -105,8 +108,16 @@ echo -e "\x1b[34m`date +%FT%H:%M:%S`: ====== Running lintian ===================
 echo -e ""
 
 changesFile=`find /var/cache/pbuilder/result/ -name "${changesFilesPattern}"`
-if [ ! -e "$changesFile" ] ; then
-    echo >&2 "ERROR: Unable to find changes file $changesFile!"
+if [ ! -e "${changesFile}" ] ; then
+    echo >&2 "ERROR: Unable to find changes file ${changesFile}!"
     exit 1
 fi
-lintian -iIEv --pedantic ${changesFilesPattern} || true
+
+profile="ubuntu"
+if [ "${PACKAGE_DISTRIBUTION}" == "unstable" -o \
+     "${PACKAGE_DISTRIBUTION}" == "testing"  -o \
+     "${PACKAGE_DISTRIBUTION}" == "stable" ] ; then
+   profile="debian"
+fi
+echo "Calling: lintian -iIEv --pedantic --profile ${profile} ${changesFile}"
+lintian -iIEv --pedantic --profile ${profile} ${changesFile} || true
